#!/bin/sh

sleep ${SEESTAR_INITIAL_DELAY:-0}

python ./seestar_run.py \
    $SEESTAR_IP \
    $SEESTAR_TARGET \
    $SEESTAR_RA \
    $SEESTAR_DEC \
    $SEESTAR_LP_FILTER \
    $SEESTAR_SESSION_TIME \
    $SEESTAR_RA_PANEL_SZ \
    $SEESTAR_DEC_PANEL_SZ \
    $SEESTAR_RA_OFFSET_FACTOR \
    $SEESTAR_DEC_OFFSET_FACTOR